# Generated by Django 4.2.1 on 2023-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_todo_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="date_due",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
